theme: jekyll-theme-minimal
title: Weasel0230's homepage
description: Bookmark this to keep an eye on my project updates! I know i turn stuff in late, i have 5 classes and work full time! I appreciate you, and thank you for the course!
